#!/bin/bash


for nb in `ls *ipynb`
do
    echo "$base"
    if [ -e "./devtools/prepare/${base}.sh" ]
    then
        echo "Running devtools/prepare/${base}.sh"
        bash ./devtools/prepare/${base}.sh
    fi
done
        
